export const GET_ALL_ITEMS_DATA = 'GET_ALL_ITEMS_DATA';
export const GET_ALL_ITEMS_DATA_ERROR = 'GET_ALL_ITEMS_DATA_ERROR';
export const GET_ALL_ITEMS_DATA_RECEIVED = 'GET_ALL_ITEMS_DATA_RECEIVED';

export const POST_NEW_ITEM_DATA = 'POST_NEW_ITEM_DATA';
export const POST_NEW_ITEM_DATA_ERROR = 'POST_NEW_ITEM_DATA_ERROR';
export const POST_NEW_ITEM_DATA_RECEIVED = 'POST_NEW_ITEM_DATA_RECEIVED';

export const INCREMENT_ID = 'INCREMENT_ID';

